pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS = credentials('mle-template')
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm   // чтобы появились docker-compose.yml и functional_test.py
            }
        }

    
            stage('Login') {
                steps {
                    bat 'docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%'
                }
            }

            stage('Pull image') {
                steps {
                    bat 'docker pull gug1/mle-template:lab1'
                }
            }

            stage('Run container') {
                steps {
                    // Очистка порта через PowerShell (без проблем с кавычками)
                    bat 'docker rm -f mle-template || exit 0'
                    bat 'for /f "tokens=*" %%i in (\'docker ps -q --filter "publish=8000"\') do docker rm -f %%i'
                    // Запуск контейнера
                    bat 'docker run --name mle-template -p 8000:8000 -d gug1/mle-template:lab1'
                    // Ждём 15 секунд, чтобы сервер точно стартовал
                    bat 'powershell -Command "Start-Sleep -Seconds 15"'
                    // Выводим логи контейнера для диагностики (можно оставить)
                    bat 'docker logs mle-template'
                }
            }

            stage('Functional test') {
                steps {
                    bat 'docker exec mle-template python functional_test.py'
                }
            }
        }

    post {
        always {
            bat 'docker rm -f mle-template || exit 0'
            bat 'docker logout'
            echo 'CD pipeline finished'
        }
    }
}
