pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS = credentials('mle-template')
    }

    options {
        timestamps()
    }

    stages {
        stage('Login') {
            steps {
                bat 'docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%'
            }
        }

        stage('Pull image') {
            steps {
                bat 'docker pull gug1/mle-template:latest'
            }
        }

        stage('Remove old container') {
            steps {
                bat 'docker rm -f mle-template || exit 0'
            }
        }

        stage('Run container') {
            steps {
                bat '''
                    docker ps -q --filter "publish=8000" > containers.txt
                    for /F %%i in (containers.txt) do docker rm -f %%i
                    docker run --name mle-template -p 8000:8000 -d gug1/mle-template:latest
                    '''
            }
        }

        stage('Functional test') {
            steps {
                bat '''
                    timeout /t 30 /nobreak
                    docker exec mle-template python tests/functional/functional_test.py
                '''
            }
        }
    }

    post {
        always {
            bat 'docker rm -f mle-template || exit 0'
            bat 'docker logout'
            echo 'CD pipeline finished'
        }
    }
}
