pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('mle-template')
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {
        stage('Checkout') {
            steps {
                checkout scm   // чтобы появились docker-compose.yml и functional_test.py
            }
        }

        stage('Login'){
            steps{
                bat 'docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%'
                }
            }

        stage('Pull image'){
            steps{
                bat '''
                        docker pull gug1/mle-template:lab4
                '''
            }
        }

       stage('Deploy with DB') {
            steps {
                // Останавливаем старые контейнеры, если остались
                bat 'powershell -Command "docker ps -q --filter publish=8000 | ForEach-Object { docker rm -f \\$_ }"'
                bat 'docker rm -f mle-template mle-postgres || exit 0'
                bat 'docker-compose down || exit 0'
                // Генерируем .env с безопасными переменными (пароль из креденшелов)
                withCredentials([usernamePassword(
                    credentialsId: 'postgres-creds',
                    usernameVariable: 'POSTGRES_USER',
                    passwordVariable: 'POSTGRES_PASSWORD'
                ),
                string(
                    credentialsId: 'vault-token',
                    variable: 'VAULT_TOKEN'
                )
                ]) {
                    bat '''
                        echo POSTGRES_DB=mle_db > .env
                        echo POSTGRES_USER=%POSTGRES_USER% >> .env
                        echo POSTGRES_PASSWORD=%POSTGRES_PASSWORD% >> .env
                        echo POSTGRES_HOST=db >> .env
                        echo POSTGRES_PORT=5432 >> .env
                    '''
                }
                // запускаем оба сервиса, без сборки
                bat 'docker-compose up -d'
                bat 'powershell -Command "Start-Sleep -Seconds 30"'
            }
        }

        stage('Functional test') {
            steps {
                // Используем Python-скрипт 
                bat 'docker exec mle-template python functional_test.py'
            }
        }
    }

    post {
        always {
            bat 'docker-compose down'
            bat 'docker logout'
            echo 'CD pipeline finished'
        }
    }
}
