pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('mle-template')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {
        stage('Clone github repository') {
            steps {
                cleanWs()
               // bat 'chcp 65001 && git clone -b main https://github.com/Gugg11/mle-template.git'
               checkout scm
				}
			}

        stage('Setup Python & install dependencies') {
            steps {
                bat 'chcp 65001 && python -m venv venv && venv\\Scripts\\activate && pip install -r requirements.txt'
                }
            }
        
        stage('Data preprocessing') {
            steps {
                bat 'chcp 65001 && venv\\Scripts\\activate && python src/preprocess.py'
                }
            }

        stage('Train model') {
            steps {
                bat 'chcp 65001 && venv\\Scripts\\activate && python src/train.py'
                }
            }    
        
        stage('Unit tests & coverage') {
            steps {
                bat '''
                    chcp 65001
                    venv\\Scripts\\activate
                    coverage run src/unit_tests/test_preprocess.py
                    coverage run -a src/unit_tests/test_training.py
                    coverage report -m
                '''
                }
            }
        
        stage('Functional test of model') {
            when {
                // Можно пропустить, если не нужен, но для надёжности оставим
                expression { return fileExists('src/predict.py') }
            }
            steps {
                bat 'chcp 65001 && venv\\Scripts\\activate && python src/predict.py -m LOG_REG -t func'
                }
            }

        stage('Login to Docker Hub') {
            steps {
                bat 'chcp 65001 && docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%'
                }
            }   

        stage('Push Docker image') {
            steps {
                bat 'chcp 65001 && docker push gug1/mle-template:latest'
                }
            }
        }     

     post {
        always {
            echo 'Pipeline finished'
            bat 'docker logout'
        }
    }
}
