pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS = credentials('mle-template')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
    }

    stages {
        stage('Clone repository') {
            steps {
                cleanWs()
                checkout scm
            }
        }

        stage('Generate secrets and build') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'postgres-creds',
                        usernameVariable: 'POSTGRES_USER',
                        passwordVariable: 'POSTGRES_PASSWORD'
                    ),
                    string(
                        credentialsId: 'vault-token',
                        variable: 'VAULT_TOKEN'
                    )
                ]) {
                    script {
                        // Генерация .env (нужен для docker-compose, но НЕ для веб-сервиса в ЛР3)
                        bat '''
                            echo POSTGRES_DB=mle_db > .env
                            echo POSTGRES_USER=%POSTGRES_USER% >> .env
                            echo POSTGRES_PASSWORD=%POSTGRES_PASSWORD% >> .env
                            echo POSTGRES_HOST=db >> .env
                            echo POSTGRES_PORT=5432 >> .env
                            echo VAULT_TOKEN=%VAULT_TOKEN% >> .env
                        '''
                        // Сборка образа
                        bat 'docker build -t gug1/mle-template:latest .'
                    }
                }
            }
        }

        stage('Start services') {
            steps {
                script {
                    // Очистка перед запуском
                    bat 'docker-compose down --remove-orphans || exit 0'
                    bat 'docker rm -f mle-template mle-postgres || exit 0'
                    bat 'docker-compose up -d'
                    bat 'powershell -Command "Start-Sleep -Seconds 25"'
                }
            }
        }

        stage('Check container logs') {
            steps {
                bat 'docker-compose logs --tail 20 web'
            }
        }

        stage('Login and Push') {
            steps {
                bat 'chcp 65001 && docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%'
                bat 'docker push gug1/mle-template:latest'
            }
        }
    }

    post {
        always {
            bat 'docker-compose down'
            echo 'CI pipeline finished'
        }
    }
}